debug = true

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

[api]

#[docker]
#domain = "docker.local"
#watch = true
#exposedByDefault = false

[consulCatalog]
endpoint = "consul:8500"
#exposedByDefault = false # You have to manually add the tags to enable the service to be discovered
domain = "docker.local"
prefix = "traefik"

[file]

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
        url = "http://127.0.0.1:50051"
        weight = 1
    [backends.backend1.servers.server2]
        url = "http://127.0.0.1:50052"
        weight = 1


[frontends]
  [frontends.frontend1]
  backend = "backend1"
    [frontends.frontend1.routes.Fetch]
    rule = "Host:frontend1.local"
    [frontends.frontend1.routes.List]
    rule = "Host:frontend1.local"
    [frontends.frontend1.routes.Echo]
    rule = "Host:frontend.local"