[api]
  insecure = true
  dashboard = true

[entrypoints]
  [entrypoints.web]
    address = ":80"

  [entrypoints.websecure]
    address = ":443"
[log]
  level = "DEBUG"

[providers]
  [providers.docker]
    exposedByDefault = true

  [providers.file]
    filename = "/etc/traefik/dyn.toml"
    watch = true